FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean

RUN apt-get install ffmpeg libsm6 libxext6  -y

WORKDIR /app

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 7860

CMD ["python3", "app.py"]
