FROM python:3.10-alpine3.20

RUN apk upgrade && apk add --no-cache ffmpeg libsm libxext
RUN apk add git
WORKDIR /app

COPY requirements.txt .
RUN python3 -m pip install --upgrade pip
RUN git clone --recursive https://github.com/pytorch/pytorch \
&& cd pytorch && python setup.py install
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 7860

CMD ["python3", "app.py"]
