name: CI CD workflow

on:
  push:
    branches:
      - main
      - duydd5_ci_cd
      - features/full-production
      - dev_duydd5_cd_gcp
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  ci:
    name : Run CI

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Create data directory
      run: |
        mkdir data && cd data && wget http://wednesday.csail.mit.edu/temporal/release/recipes_with_nutritional_info.json
 
    - name: Clean up Docker space
      run: docker system prune -af

    - name: Build and start containers with Docker Compose
      run: |
        docker compose up -d

    - name: Build Vector database
      run: |
        docker run --rm -v "$(pwd)":/app --network host ai_cookbook_app python3 create_db.py

    - name: Run unit tests
      run: |
        docker run --rm -v "$(pwd)":/app --network host ai_cookbook_app python -m unittest discover -s unitTest
  
  cd: 
    name: Deploy to GCP
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          export_default_credentials: true
    
    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
          project_id: '${{ secrets.PROJECT_ID }}'
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: '${{ secrets.DOCKER_USER }}'
        password: '${{ secrets.DOCKER_ACCESS_TOKEN }}'

    - name: Build and push Docker images
      run: |
        docker compose build
        docker tag ai_cookbook_app ${{ secrets.DOCKER_USER }}/ai_cookbook_app
        docker push ${{ secrets.DOCKER_USER }}/ai_cookbook_app

    - name: Upload source code to GCE
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 34.124.135.34
        username: ${{ secrets.GCE_SSH_USERNAME }}
        key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
        source: "."
        target: "/home/${{ secrets.GCE_SSH_USERNAME }}/app"

    - name: SSH into GCE and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 34.124.135.34
        username: ${{ secrets.GCE_SSH_USERNAME }} 
        key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USER }}/ai_cookbook_app
          docker tag ${{ secrets.DOCKER_USER }}/ai_cookbook_app:latest ai_cookbook_app
          cd /home/${{ secrets.GCE_SSH_USERNAME }}/app
          docker compose up --detach --build --force-recreate