name: CI CD workflow

on:
  push:
    branches:
      - main
      - duydd5_ci_cd
      - features/full-production
      - dev_duydd5_cd_gcp
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  ci:
    name : Run CI
    strategy: 
      matrix: 
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assumes you have a requirements.txt with necessary dependencies

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and start containers with Docker Compose
      run: |
        docker compose up -d

    - name: Create data directory
      run: |
        mkdir data && cd data && wget http://wednesday.csail.mit.edu/temporal/release/recipes_with_nutritional_info.json

    - name: Build Vector database
      run: |
        python create_db.py

    - name: Run unit tests
      run: |
        python -m unittest discover -s unitTest
  
  cd: 
    name: Deploy to GCP
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
          project_id: tidal-beacon-449208-f0
    

  